// eslint-disable-next-line import/prefer-default-export
export const string = {
  LOG_IN: 'Log In',
  LOGIN: 'Login',
  EMAIL: 'Email',
  PASSSWORD: 'Password',
  EMAIL_PLACEHOLDER: 'Email goes here',
  PASSSWORD_PLACEHOLDER: 'Password goes here',
  FB_LOGIN: 'Login with Facebook',
  DETAIL: 'Detail',
  NAME: 'Name',
  NAME_PLACEHOLDER: 'User name goes here',
  CONTACT_NO: 'Contact Number',
  CONTACT_PLACEHOLDER: 'Contact number goes here',
  ACTIVE: 'Active',
  SAVE: 'Save',
  CANCEL: 'Cancel',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  ADDRESS_BOOK: 'Address Book',
  SEARCH: 'Search name...',
  LOADING: 'Loading...',
  NO_DATA: 'No Data',
  ASYNC_USERTOKEN: 'userToken',
  ASYNC_DATA: 'Data',
  ASYNC_USERNAME: 'username',
  ASYNC_PWD: 'pwd',
};
